---
- name: Install sonarqube
  hosts: docker 
  become: true

  tasks:
        
    - name: Install the latest version of docker 
      ansible.builtin.dnf:
        name: docker 
        state: latest 

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Enable service docker, if not enabled
      ansible.builtin.service:
        name: docker
        enabled: yes
